### ISSUE TITLE
clearTimeOut not cancelling proposed functions...

### ISSUE THREAD

**Issue by Alexandroidd** [Alexandroidd/Samurai-Slash#1]
https://www.w3schools.com/jsref/met_win_cleartimeout.asp
http://stackoverflow.com/questions/7173419/cleartimeout-not-working

Having trouble understanding why my clearTimeout isn't working. This is in relation to having a "False Start" with my game or whether it should continue on as planned....

**Comment by ZebGirouard** [comment]
Woo hoo clearTimeout!  The "missed connections page" of Javascript.  Great work troubleshooting, @Alexandroidd !
